/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'sport' : Sport,
}
export interface Event {
  'id' : bigint,
  'status' : EventStatus,
  'title' : string,
  'date' : Time,
  'description' : string,
  'sport' : Sport,
  'location' : string,
}
export type EventStatus = { 'upcoming' : null } |
  { 'completed' : null };
export type Sport = { 'football' : null } |
  { 'general' : null } |
  { 'badminton' : null };
export type Time = bigint;
export interface Venue {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'sport' : Sport,
  'location' : string,
}
export interface _SERVICE {
  'addAnnouncement' : ActorMethod<[string, string, Sport, Time], bigint>,
  'addEvent' : ActorMethod<
    [string, Sport, Time, string, string, EventStatus],
    bigint
  >,
  'addVenue' : ActorMethod<[string, Sport, string, string], bigint>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getEventsBySport' : ActorMethod<[Sport], Array<Event>>,
  'getUpcomingEvents' : ActorMethod<[], Array<Event>>,
  'getVenues' : ActorMethod<[], Array<Venue>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];