/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Sport = IDL.Variant({
  'football' : IDL.Null,
  'general' : IDL.Null,
  'badminton' : IDL.Null,
});
export const Time = IDL.Int;
export const EventStatus = IDL.Variant({
  'upcoming' : IDL.Null,
  'completed' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'sport' : Sport,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'status' : EventStatus,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'sport' : Sport,
  'location' : IDL.Text,
});
export const Venue = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sport' : Sport,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAnnouncement' : IDL.Func(
      [IDL.Text, IDL.Text, Sport, Time],
      [IDL.Nat],
      [],
    ),
  'addEvent' : IDL.Func(
      [IDL.Text, Sport, Time, IDL.Text, IDL.Text, EventStatus],
      [IDL.Nat],
      [],
    ),
  'addVenue' : IDL.Func([IDL.Text, Sport, IDL.Text, IDL.Text], [IDL.Nat], []),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getEventsBySport' : IDL.Func([Sport], [IDL.Vec(Event)], ['query']),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getVenues' : IDL.Func([], [IDL.Vec(Venue)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Sport = IDL.Variant({
    'football' : IDL.Null,
    'general' : IDL.Null,
    'badminton' : IDL.Null,
  });
  const Time = IDL.Int;
  const EventStatus = IDL.Variant({
    'upcoming' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'sport' : Sport,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'status' : EventStatus,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'sport' : Sport,
    'location' : IDL.Text,
  });
  const Venue = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sport' : Sport,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'addAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, Sport, Time],
        [IDL.Nat],
        [],
      ),
    'addEvent' : IDL.Func(
        [IDL.Text, Sport, Time, IDL.Text, IDL.Text, EventStatus],
        [IDL.Nat],
        [],
      ),
    'addVenue' : IDL.Func([IDL.Text, Sport, IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getEventsBySport' : IDL.Func([Sport], [IDL.Vec(Event)], ['query']),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getVenues' : IDL.Func([], [IDL.Vec(Venue)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };