/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Announcement {
    id: bigint;
    title: string;
    content: string;
    createdAt: Time;
    sport: Sport;
}
export type Time = bigint;
export interface Venue {
    id: bigint;
    name: string;
    description: string;
    sport: Sport;
    location: string;
}
export interface Event {
    id: bigint;
    status: EventStatus;
    title: string;
    date: Time;
    description: string;
    sport: Sport;
    location: string;
}
export enum EventStatus {
    upcoming = "upcoming",
    completed = "completed"
}
export enum Sport {
    football = "football",
    general = "general",
    badminton = "badminton"
}
export interface backendInterface {
    addAnnouncement(title: string, content: string, sport: Sport, createdAt: Time): Promise<bigint>;
    addEvent(title: string, sport: Sport, date: Time, location: string, description: string, status: EventStatus): Promise<bigint>;
    addVenue(name: string, sport: Sport, location: string, description: string): Promise<bigint>;
    getAnnouncements(): Promise<Array<Announcement>>;
    getEvents(): Promise<Array<Event>>;
    getEventsBySport(sport: Sport): Promise<Array<Event>>;
    getUpcomingEvents(): Promise<Array<Event>>;
    getVenues(): Promise<Array<Venue>>;
}
import type { Announcement as _Announcement, Event as _Event, EventStatus as _EventStatus, Sport as _Sport, Time as _Time, Venue as _Venue } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAnnouncement(arg0: string, arg1: string, arg2: Sport, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addAnnouncement(arg0, arg1, to_candid_Sport_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAnnouncement(arg0, arg1, to_candid_Sport_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addEvent(arg0: string, arg1: Sport, arg2: Time, arg3: string, arg4: string, arg5: EventStatus): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(arg0, to_candid_Sport_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_EventStatus_n3(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(arg0, to_candid_Sport_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, to_candid_EventStatus_n3(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addVenue(arg0: string, arg1: Sport, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addVenue(arg0, to_candid_Sport_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVenue(arg0, to_candid_Sport_n1(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async getAnnouncements(): Promise<Array<Announcement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnnouncements();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnnouncements();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvents();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvents();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventsBySport(arg0: Sport): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventsBySport(to_candid_Sport_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventsBySport(to_candid_Sport_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUpcomingEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingEvents();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingEvents();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVenues(): Promise<Array<Venue>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVenues();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVenues();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Announcement_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Announcement): Announcement {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_EventStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventStatus): EventStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Sport_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sport): Sport {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Venue_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Venue): Venue {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EventStatus;
    title: string;
    date: _Time;
    description: string;
    sport: _Sport;
    location: string;
}): {
    id: bigint;
    status: EventStatus;
    title: string;
    date: Time;
    description: string;
    sport: Sport;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_EventStatus_n13(_uploadFile, _downloadFile, value.status),
        title: value.title,
        date: value.date,
        description: value.description,
        sport: from_candid_Sport_n8(_uploadFile, _downloadFile, value.sport),
        location: value.location
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    description: string;
    sport: _Sport;
    location: string;
}): {
    id: bigint;
    name: string;
    description: string;
    sport: Sport;
    location: string;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        sport: from_candid_Sport_n8(_uploadFile, _downloadFile, value.sport),
        location: value.location
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    content: string;
    createdAt: _Time;
    sport: _Sport;
}): {
    id: bigint;
    title: string;
    content: string;
    createdAt: Time;
    sport: Sport;
} {
    return {
        id: value.id,
        title: value.title,
        content: value.content,
        createdAt: value.createdAt,
        sport: from_candid_Sport_n8(_uploadFile, _downloadFile, value.sport)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upcoming: null;
} | {
    completed: null;
}): EventStatus {
    return "upcoming" in value ? EventStatus.upcoming : "completed" in value ? EventStatus.completed : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    football: null;
} | {
    general: null;
} | {
    badminton: null;
}): Sport {
    return "football" in value ? Sport.football : "general" in value ? Sport.general : "badminton" in value ? Sport.badminton : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Venue>): Array<Venue> {
    return value.map((x)=>from_candid_Venue_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Announcement>): Array<Announcement> {
    return value.map((x)=>from_candid_Announcement_n6(_uploadFile, _downloadFile, x));
}
function to_candid_EventStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): _EventStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Sport_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): _Sport {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sport): {
    football: null;
} | {
    general: null;
} | {
    badminton: null;
} {
    return value == Sport.football ? {
        football: null
    } : value == Sport.general ? {
        general: null
    } : value == Sport.badminton ? {
        badminton: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): {
    upcoming: null;
} | {
    completed: null;
} {
    return value == EventStatus.upcoming ? {
        upcoming: null
    } : value == EventStatus.completed ? {
        completed: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
